In [1]:
import torch as t
import numpy as np

In [5]:
x = t.rand(5,3)

x

tensor([[0.9716, 0.3511, 0.0765],
        [0.2764, 0.1584, 0.6575],
        [0.7797, 0.2164, 0.4802],
        [0.4344, 0.6139, 0.3538],
        [0.5538, 0.2557, 0.7757]])

In [10]:
print(x.size())
x.size()[1]
x.size()[0]

torch.Size([5, 3])


5

In [11]:
y = t.rand(5,3)

In [12]:
x+y

tensor([[1.5918, 1.1196, 0.5376],
        [0.3239, 1.1549, 1.5667],
        [1.2964, 0.5171, 0.8963],
        [0.5816, 1.3863, 0.4801],
        [0.6921, 0.3324, 1.4262]])

In [14]:
t.add(x,y)

tensor([[1.5918, 1.1196, 0.5376],
        [0.3239, 1.1549, 1.5667],
        [1.2964, 0.5171, 0.8963],
        [0.5816, 1.3863, 0.4801],
        [0.6921, 0.3324, 1.4262]])

In [17]:
a =t.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [19]:
b=a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [20]:
a= np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [21]:
b=t.from_numpy(a)

In [22]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [25]:
if t.cuda.is_available():
    x=x.cuda
    y=y.cuda
    xx=x+y

In [26]:
xx

NameError: name 'xx' is not defined

In [3]:
from torch.autograd import Variable

In [4]:
x=Variable(t.ones(2,2),requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [5]:
y=x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [6]:
y.grad_fn

In [7]:
y.backward()

In [8]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [9]:
y.backward()
x.grad()

TypeError: 'Tensor' object is not callable

In [16]:
x.grad.data.zero_()

tensor([[0., 0.],
        [0., 0.]])

In [17]:
y.backward()

In [18]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [57]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16,5)
        
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
        
    def forward(self, x):
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        x = F.max_pool2d(F.relu(self.conv2(x)), (2, 2))
        x = x.view(x.size()[0], -1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
net = Net()
print(net)
        


Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [58]:
params = list(net.parameters())
print(len(params))

10


In [54]:
for name,parameters in net.named_parameters():
    print(name,':',parameters.size())

conv1.weight : torch.Size([6, 1, 5, 5])
conv1.bias : torch.Size([6])
conv2.weight : torch.Size([16, 6, 5, 5])
conv2.bias : torch.Size([16])
fc1.weight : torch.Size([120, 400])
fc1.bias : torch.Size([120])
fc2.weight : torch.Size([84, 120])
fc2.bias : torch.Size([84])
fc3.weight : torch.Size([10, 84])
fc3.bias : torch.Size([10])


In [59]:
input = Variable(t.randn(1,1,32,32))
#out = net(input)
#out.size()

In [60]:
net.zero_grad()
out.backward(Variable(t.ones(1,10)))

In [61]:
output = net(input)
target = Variable(t.arange(0,10))
target = target.view(-1).float()
criterion = nn.MSELoss()
loss = criterion(output, target)
loss

C:\Users\studentx\Anaconda3\lib\site-packages\torch\nn\modules\loss.py:443: UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


tensor(28.3942, grad_fn=<MseLossBackward>)

In [44]:
net.zero_grad()
print(net.conv1.bias.grad)

tensor([0., 0., 0., 0., 0., 0.])


In [45]:
loss.backward()
print(net.conv1.bias.grad)

tensor([ 0.0728, -0.0752,  0.0300, -0.1016, -0.0300,  0.0076])


In [62]:
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr = 0.01)
optimizer.zero_grad()
ouput = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()

C:\Users\studentx\Anaconda3\lib\site-packages\torch\nn\modules\loss.py:443: UserWarning: Using a target size (torch.Size([10])) that is different to the input size (torch.Size([1, 10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)



autograd


In [65]:
import torch as t
from torch.autograd import Variable as V

In [67]:
x = V(t.ones(1))
b = V(t.rand(1), requires_grad = True)
w = V(t.rand(1), requires_grad = True)
y = w*x
z = y+b

In [68]:
x.requires_grad, b.requires_grad, w.requires_grad

(False, True, True)

In [69]:
y.requires_grad

True

In [70]:
x.is_leaf, w.is_leaf, b.is_leaf

(True, True, True)

In [71]:
y.is_leaf, z.is_leaf

(False, False)

In [72]:
z.grad_fn

In [73]:
y.grad_fn

In [74]:
z.grad_fn.next_functions

((<MulBackward0 at 0x26bb12a4cf8>, 0), (<AccumulateGrad at 0x26bb0e18400>, 0))